// <auto-generated />
namespace ControleDeContatos.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AjustarCampos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AjustarCampos));
        
        string IMigrationMetadata.Id
        {
            get { return "202503251850253_AjustarCampos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
