// <auto-generated />
namespace ControleDeContatos.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class IniciandoBanco : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IniciandoBanco));
        
        string IMigrationMetadata.Id
        {
            get { return "202503251430531_IniciandoBanco"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
